export const PASSWORD_MINIMUM_LENGTH = 12;
export const PASSWORD_MINIMUM_UPPER_CASE = 1;
export const PASSWORD_MINIMUM_LOWER_CASE = 1;
export const PASSWORD_MINIMUM_NUMERIC = 1;
export const PASSWORD_MINIMUM_SPECIAL = 1;
